Exploring Gun Deaths in America
================

## Objectives

  - To explore gun death data curated by FiveThirtyEight - \[original
    data available here\] -
    (<https://github.com/fivethirtyeight/guns-data>) by
      - Month
      - Intent
      - Age and sex
      - Education
      - Season
      - Intent by race
      - Police-relatedness

## Read in the data

The gun\_deaths.csv is provided in the repository.

``` r
library(tidyverse)    # load tidyverse packages, including ggplot2
library(knitr)
library(devtools)

# read in the data
gun_data <- read.csv("gun_deaths.csv")
```

## Generating a data frame that summarizes the number of gun deaths per month and printing using `kable()`.

Knitr is part of the knitr package. Allows you to change column names
and add captions and make pretty tables in your knitted document. Hint:
set the argument format = “markdown”

``` r
monthly_gun_data <- gun_data %>%
    select(month) %>%
    mutate(month = factor(month.abb[month], 
                          levels = c("Jan", "Feb","Mar", "Apr", "May", 
                                     "Jun", "Jul", "Aug","Sep", "Oct", "Nov", "Dec"))) %>%
    group_by(month) %>%
    count()

kable(monthly_gun_data, format = "markdown",
      col.names = c("Month", "Total Deaths"),
      caption = "Total Gun Deaths from 2012-2014 by Month")
```

| Month | Total Deaths |
| :---- | -----------: |
| Jan   |         8273 |
| Feb   |         7093 |
| Mar   |         8289 |
| Apr   |         8455 |
| May   |         8669 |
| Jun   |         8677 |
| Jul   |         8989 |
| Aug   |         8783 |
| Sep   |         8508 |
| Oct   |         8406 |
| Nov   |         8243 |
| Dec   |         8413 |

### Generating a bar chart with human-readable labels on the x-axis. That is, each month should be labeled “Jan”, “Feb”, “Mar” (full or abbreviated month names are fine), not `1`, `2`, `3`.

``` r
# creating a theme to use for all further plots
theme04 <- theme(plot.subtitle = element_text (hjust = 0.5),
            plot.title = element_text(size = 15, hjust = 0.5),
            axis.line = element_line(color = "grey60", size = 0.3),
            axis.text.x = element_text(size = 7),
            axis.title.x= element_text(vjust = -1),
            panel.background = element_blank()) 

# generating a barplot to show the gun deaths per month
ggplot(monthly_gun_data, mapping = aes(x = month, y = n)) +
    geom_col(fill = "skyblue") +
    geom_text(aes(label = n), vjust = -0.5, size = 3, color = "grey40") +

# making the plot prettier
     labs(title = "US Gun Deaths by Month (2012-2014)", 
       x = "Month", 
       y = "Number of Deaths",
       caption = "Source: FiveThirtyEight") +
# adding theme
    theme04
```

![](HW04_files/figure-gfm/month_chart-1.png)<!-- -->

## Generating a bar chart that identifies the number of gun deaths associated with each type of intent cause of death. The bars should be sorted from highest to lowest values.

``` r
gun_data %>%
# counting observations with each "intent" type
    count(intent) %>%
# generating a graph displaying the counts
ggplot(mapping = aes(reorder(intent, -n), n)) +
    geom_col(fill = "skyblue") + 
# adding data labels because of large range 
    geom_text(aes(label = n), vjust = -0.5, size = 3, color = "grey40") +
# making the graph nicer
    labs(title = "US Gun Deaths by Intent (2012-2014)", 
       x = "Intent of Incident", 
       y = "Number of Deaths",
       caption = "Source: FiveThirtyEight") +
# adding theme
    theme04
```

![](HW04_files/figure-gfm/intent-1.png)<!-- -->

## Generating a boxplot visualizing the age of gun death victims, by sex. Print the average age of female gun death victims.

``` r
#removing data points for which age is not available
data_with_sex <- gun_data %>%
    filter(age != "Not Available") %>%
    mutate(age = as.numeric(age))

# generating a boxplot visualizing the data
ggplot(data_with_sex, mapping = aes(x = sex, y = age)) +
    geom_boxplot(fill = "skyblue") +

# adding labels
     labs(title = "Ages of Gun Death Victims", 
          subtitle = "Age Distributions of US Gun Death Victims, by Sex, in the United States from 2012 to 2014",
          x = "Sex", 
          y = "Age (Years)",
          caption = "Source: FiveThirtyEight") + 
    scale_x_discrete(breaks=c("F", "M"),
                      labels=c("Female", "Male")) +
    
# adding a theme
    theme04
```

![](HW04_files/figure-gfm/age_&_sex-1.png)<!-- -->

``` r
# calculating the mean age of female gun death victims
data_with_sex %>%
    filter(sex == "F") %>%
    summarize(average_female_age = mean(age))
```

    ##   average_female_age
    ## 1           44.14648

**The average age of the female gun death victims in this dataset is
44.15
years.**

## How many white males with at least a high school education were killed by guns in 2012?

``` r
gun_data %>%
# filtering for all of the specified criteria
    filter(year == 2012, 
           race == "White", 
           education != "Less than HS",
           sex == "M") %>%
# counting the remaining observations, which will determine the answer
    count()
```

    ## # A tibble: 1 x 1
    ##       n
    ##   <int>
    ## 1 15484

**In 2012, 15,484 white males with at least a high school education were
killed by guns in 2012.**

## Which season of the year has the most gun deaths?

Assume that:

  - Winter = January-March
  - Spring = April-June
  - Summer = July-September
  - Fall =
October-December

# These are more open ended questions from here on out, you could look at making multiple summaries or types of plots.

### Are whites who are killed by guns more likely to die because of suicide or homicide? How does this compare to blacks and hispanics?

``` r
# creating a new datafram that includes counts for intent by race, filters for the 3 requested races, and only includes homicides and suicides
race_intent_data <- gun_data %>%
    select(race, intent) %>%
    filter(race %in% c("White", "Black", "Hispanic"),
           intent %in% c("Suicide", "Homicide")) %>%
    group_by(race, intent) %>%
    count() %>%
    ungroup()
```

(hint maybe looking at percentages would be good)

``` r
# generate a stacked barplot to visualize intent by race
ggplot(race_intent_data, mapping = aes(x = race, y = n, fill = intent)) + 
    geom_col(position = "fill") +

# adding labels for legibility 
    labs(title = "Homicide and Suicide Gun Deaths by Race", 
          subtitle = "Proportion of US Gun Deaths, by Race, from Homicide vs. Suicide from 2012-2014",
          x = "Race", 
          y = "Proportion of Total Deaths",
          caption = "Source: FiveThirtyEight",
          fill = "Intent") + 

# changing colors
    scale_fill_manual(values = c("skyblue", "palevioletred2")) +

# adding a theme
    theme04
```

![](HW04_files/figure-gfm/race_2-1.png)<!-- --> **According to this
graph, whites killed by guns are more likely to die by suicide (~85%)
than by homicide. Blacks and Hispanics, on the other hand, are more
likely to die by homicide (~85% and ~70%,
respectively).**

### Are police-involved gun deaths significantly different from other gun deaths? Assess the relationship between police involvement and age, police involvement and race, and the intersection of all three variables.

``` r
# cleaning up the dataset to contain only the needed variables, removing any instances of age being unavailable
police_data <- gun_data %>%
    select(police, age, race) %>%
    filter(age != "Not Available") %>%
    mutate(age = as.numeric(age)) %>%
    group_by(police)

# changing one variable to allow for cleaner labeling
police_data$race <- gsub(pattern = "Not Availabletive American/Not Availabletive Alaskan", 
     replacement = "Not Available",
     x = police_data$race)

# creating a boxplot to visualize the age distributions in each case
ggplot(police_data, mapping = aes(x = factor(police), y = age)) +
    geom_boxplot(fill = "skyblue", outlier.shape = NA) +
    
# adding labels
     labs(title = "Ages of Gun Death Victims by Police Involvement", 
          subtitle = "Age Distributions of US Gun Death Victims, by Police Involvement, \n in the United States from 2012 to 2014",
          x = "Police Involvement", 
          y = "Age (Years)",
          caption = "Source: FiveThirtyEight") + 
    scale_x_discrete(breaks=c("0", "1"),
                      labels=c("Uninvolved", "Involved")) +
    
# adding a theme
    theme04
```

![](HW04_files/figure-gfm/police-1.png)<!-- -->

Think about performing stats such as a t.test to see if differences you
are plotting are statistically significant

``` r
# creating two seperate datasets basd on police involvement
age_police_uninvolved <- police_data %>%
    filter(police == 0) 
age_police_involved <- police_data %>%
    filter(police == 1) 

# use new datasets to conduct t test
t.test(age_police_uninvolved$age, age_police_involved$age)
```

    ## 
    ##  Welch Two Sample t-test
    ## 
    ## data:  age_police_uninvolved$age and age_police_involved$age
    ## t = 22.927, df = 1490.8, p-value < 2.2e-16
    ## alternative hypothesis: true difference in means is not equal to 0
    ## 95 percent confidence interval:
    ##  8.135922 9.658342
    ## sample estimates:
    ## mean of x mean of y 
    ##  44.11183  35.21469

**The t-test suggests that the difference in age is statistically
significant.**

``` r
# manipulating dataset to calculate percentage of instances (for each race) with police involvement 
race_and_police <- police_data %>%
    group_by(race, police) %>%
    count(police) %>%
    ungroup() %>%
    group_by(race) %>%
    mutate(total = sum(n)) %>%
    filter(police == 1) %>%
    mutate(percentage_involved = n/total *100)

# generate a column graph to evaluate the rates of police involvement in each race
ggplot(race_and_police, mapping = aes(x = reorder(race, -percentage_involved),  y = percentage_involved)) + 
    geom_col(fill = "skyblue") +

# adding labels for legibility 
    labs(title = "Police Involvement in Gun Deaths, by Race", 
          subtitle = "Percentage of US Gun Deaths, by Race, with Police Involvement from 2012-2014",
          x = "Race", 
          y = "Percentage of Gun Death Instances with Police Involvement",
          caption = "Source: FiveThirtyEight") + 
    
# adding a theme
    theme04
```

![](HW04_files/figure-gfm/police_2-1.png)<!-- -->

Finally, all together
now:

``` r
# creating a boxplot to visualize the age distributions in each case, faceted by race
ggplot(police_data, mapping = aes(x = factor(police), y = age)) +
    geom_boxplot(fill = "skyblue", outlier.shape = NA) +
    facet_wrap(~race, nrow=1) +
    
# adding labels
     labs(title = "Ages of Gun Death Victims by Police Involvement and Race", 
          subtitle = "Age Distributions of US Gun Death Victims, \n by Police Involvement and Race, in the United States from 2012 to 2014",
          x = "Police Involvement", 
          y = "Age (Years)",
          caption = "Source: FiveThirtyEight") + 
    scale_x_discrete(breaks=c("0", "1"),
                      labels=c("Uninvolved", "Involved")) +
    
# adding a theme
    theme04
```

![](HW04_files/figure-gfm/police_3-1.png)<!-- -->

## Session info

``` r
# always good to have this for reproducibility purposes
devtools::session_info()
```

    ## ─ Session info ──────────────────────────────────────────────────────────
    ##  setting  value                       
    ##  version  R version 3.6.1 (2019-07-05)
    ##  os       macOS Catalina 10.15.5      
    ##  system   x86_64, darwin15.6.0        
    ##  ui       X11                         
    ##  language (EN)                        
    ##  collate  en_US.UTF-8                 
    ##  ctype    en_US.UTF-8                 
    ##  tz       America/New_York            
    ##  date     2020-07-26                  
    ## 
    ## ─ Packages ──────────────────────────────────────────────────────────────
    ##  package     * version date       lib source        
    ##  assertthat    0.2.1   2019-03-21 [1] CRAN (R 3.6.0)
    ##  backports     1.1.4   2019-04-10 [1] CRAN (R 3.6.0)
    ##  broom         0.5.2   2019-04-07 [1] CRAN (R 3.6.0)
    ##  callr         3.4.3   2020-03-28 [1] CRAN (R 3.6.2)
    ##  cellranger    1.1.0   2016-07-27 [1] CRAN (R 3.6.0)
    ##  cli           2.0.2   2020-02-28 [1] CRAN (R 3.6.0)
    ##  colorspace    1.4-1   2019-03-18 [1] CRAN (R 3.6.0)
    ##  crayon        1.3.4   2017-09-16 [1] CRAN (R 3.6.0)
    ##  desc          1.2.0   2018-05-01 [1] CRAN (R 3.6.0)
    ##  devtools    * 2.3.1   2020-07-21 [1] CRAN (R 3.6.2)
    ##  digest        0.6.21  2019-09-20 [1] CRAN (R 3.6.0)
    ##  dplyr       * 0.8.3   2019-07-04 [1] CRAN (R 3.6.0)
    ##  ellipsis      0.3.0   2019-09-20 [1] CRAN (R 3.6.0)
    ##  evaluate      0.14    2019-05-28 [1] CRAN (R 3.6.0)
    ##  fansi         0.4.0   2018-10-05 [1] CRAN (R 3.6.0)
    ##  forcats     * 0.4.0   2019-02-17 [1] CRAN (R 3.6.0)
    ##  fs            1.3.1   2019-05-06 [1] CRAN (R 3.6.0)
    ##  generics      0.0.2   2018-11-29 [1] CRAN (R 3.6.0)
    ##  ggplot2     * 3.2.1   2019-08-10 [1] CRAN (R 3.6.0)
    ##  glue          1.3.1   2019-03-12 [1] CRAN (R 3.6.0)
    ##  gtable        0.3.0   2019-03-25 [1] CRAN (R 3.6.0)
    ##  haven         2.1.1   2019-07-04 [1] CRAN (R 3.6.0)
    ##  highr         0.8     2019-03-20 [1] CRAN (R 3.6.0)
    ##  hms           0.5.1   2019-08-23 [1] CRAN (R 3.6.0)
    ##  htmltools     0.3.6   2017-04-28 [1] CRAN (R 3.6.0)
    ##  httr          1.4.1   2019-08-05 [1] CRAN (R 3.6.0)
    ##  jsonlite      1.7.0   2020-06-25 [1] CRAN (R 3.6.2)
    ##  knitr       * 1.25    2019-09-18 [1] CRAN (R 3.6.0)
    ##  labeling      0.3     2014-08-23 [1] CRAN (R 3.6.0)
    ##  lattice       0.20-38 2018-11-04 [1] CRAN (R 3.6.1)
    ##  lazyeval      0.2.2   2019-03-15 [1] CRAN (R 3.6.0)
    ##  lifecycle     0.1.0   2019-08-01 [1] CRAN (R 3.6.0)
    ##  lubridate     1.7.4   2018-04-11 [1] CRAN (R 3.6.0)
    ##  magrittr      1.5     2014-11-22 [1] CRAN (R 3.6.0)
    ##  memoise       1.1.0   2017-04-21 [1] CRAN (R 3.6.0)
    ##  modelr        0.1.5   2019-08-08 [1] CRAN (R 3.6.0)
    ##  munsell       0.5.0   2018-06-12 [1] CRAN (R 3.6.0)
    ##  nlme          3.1-140 2019-05-12 [1] CRAN (R 3.6.1)
    ##  pillar        1.4.2   2019-06-29 [1] CRAN (R 3.6.0)
    ##  pkgbuild      1.1.0   2020-07-13 [1] CRAN (R 3.6.2)
    ##  pkgconfig     2.0.3   2019-09-22 [1] CRAN (R 3.6.0)
    ##  pkgload       1.1.0   2020-05-29 [1] CRAN (R 3.6.2)
    ##  prettyunits   1.0.2   2015-07-13 [1] CRAN (R 3.6.0)
    ##  processx      3.4.1   2019-07-18 [1] CRAN (R 3.6.0)
    ##  ps            1.3.0   2018-12-21 [1] CRAN (R 3.6.0)
    ##  purrr       * 0.3.4   2020-04-17 [1] CRAN (R 3.6.2)
    ##  R6            2.4.0   2019-02-14 [1] CRAN (R 3.6.0)
    ##  Rcpp          1.0.2   2019-07-25 [1] CRAN (R 3.6.0)
    ##  readr       * 1.3.1   2018-12-21 [1] CRAN (R 3.6.0)
    ##  readxl        1.3.1   2019-03-13 [1] CRAN (R 3.6.0)
    ##  remotes       2.2.0   2020-07-21 [1] CRAN (R 3.6.2)
    ##  rlang         0.4.7   2020-07-09 [1] CRAN (R 3.6.2)
    ##  rmarkdown     1.15    2019-08-21 [1] CRAN (R 3.6.0)
    ##  rprojroot     1.3-2   2018-01-03 [1] CRAN (R 3.6.0)
    ##  rstudioapi    0.11    2020-02-07 [1] CRAN (R 3.6.0)
    ##  rvest         0.3.4   2019-05-15 [1] CRAN (R 3.6.0)
    ##  scales        1.0.0   2018-08-09 [1] CRAN (R 3.6.0)
    ##  sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 3.6.0)
    ##  stringi       1.4.3   2019-03-12 [1] CRAN (R 3.6.0)
    ##  stringr     * 1.4.0   2019-02-10 [1] CRAN (R 3.6.0)
    ##  testthat      2.3.2   2020-03-02 [1] CRAN (R 3.6.0)
    ##  tibble      * 2.1.3   2019-06-06 [1] CRAN (R 3.6.0)
    ##  tidyr       * 1.0.0   2019-09-11 [1] CRAN (R 3.6.0)
    ##  tidyselect    0.2.5   2018-10-11 [1] CRAN (R 3.6.0)
    ##  tidyverse   * 1.2.1   2017-11-14 [1] CRAN (R 3.6.0)
    ##  usethis     * 1.6.1   2020-04-29 [1] CRAN (R 3.6.2)
    ##  utf8          1.1.4   2018-05-24 [1] CRAN (R 3.6.0)
    ##  vctrs         0.2.0   2019-07-05 [1] CRAN (R 3.6.0)
    ##  withr         2.1.2   2018-03-15 [1] CRAN (R 3.6.0)
    ##  xfun          0.9     2019-08-21 [1] CRAN (R 3.6.0)
    ##  xml2          1.2.2   2019-08-09 [1] CRAN (R 3.6.0)
    ##  yaml          2.2.0   2018-07-25 [1] CRAN (R 3.6.0)
    ##  zeallot       0.1.0   2018-01-28 [1] CRAN (R 3.6.0)
    ## 
    ## [1] /Library/Frameworks/R.framework/Versions/3.6/Resources/library
